/** Color Actions */
export const ADD_COLOR_SUCCESS = 'ADD_COLOR_SUCCESS';
export const LOAD_COLORS_SUCCESS = 'LOAD_COLORS_SUCCESS';

/** Property View Actions */
export const LOAD_PROPERTY_VIEW_SUCCESS = 'LOAD_PROPERTY_VIEW_SUCCESS';
export const SWITCH_PROPERTY_VIEW_SUCCESS = 'SWITCH_PROPERTY_VIEW_SUCCESS';
